export class Colors {
  static readonly Background: string = '#020A24';
  static readonly BackgroundSoft: string = '#061435';
  static readonly PanelBg: string = '#071B43';
  static readonly PanelBgBright: string = '#0A2554';
  static readonly Border: string = '#138DCE';
  static readonly BorderSoft: string = '#123E73';
  static readonly Cyan: string = '#43D9FF';
  static readonly Title: string = '#EAF8FF';
  static readonly TextNormal: string = '#8EABD0';
  static readonly TextMuted: string = '#56739D';
  static readonly Normal: string = '#26E6B0';
  static readonly Warning: string = '#FFC857';
  static readonly Danger: string = '#FF6178';
}
